### ISSUE TITLE
if: Symbol’s function definition is void: xor

### ISSUE THREAD

**Issue by zzp0** [muffinmad/emacs-ibuffer-project#1]
Thanks for your package:)
The commit 35f00a965fa46ee0d8ceba4b05df47558aea6eff breaks ibuffer.

1. `emacs -Q -l ibuffer-project.el `
2. minimal config
```
(add-hook 'ibuffer-hook
          (lambda ()
            (setq ibuffer-filter-groups (ibuffer-project-generate-filter-groups))
            (unless (eq ibuffer-sorting-mode 'project-file-relative)
              (ibuffer-do-sort-by-project-file-relative))))
```
3. `if: Symbol’s function definition is void: xor`
The array.el xor is not an autoloaded function.

**Comment by muffinmad** [comment]
Thank for the report!

`xor` is added to `subr.el` in Emacs 27: https://github.com/emacs-mirror/emacs/commit/c676444a43e4634c1f98ec286b5bd9e46b23216b

Must be fixed now.

**Comment by basil-conto** [comment]
> `xor` is added to `subr.el` in Emacs 27: emacs-mirror/emacs@c676444

Yes, but it previously existed in `array.el` since before Emacs 20, so you can safely do the following:

```el
(autoload 'xor "array")
```

In Emacs versions prior to 27 this will ensure `xor` is `functionp`, and in Emacs 27 it will be a no-op, since `xor` will already be `fboundp`.

**Comment by muffinmad** [comment]
@basil-conto Thanks!

I stick with current solution for now. Or is it has some drawbacks?

**Comment by basil-conto** [comment]
> Or is it has some drawbacks?

Apart from readability, no.  Perhaps a comment would help convey the intention.

**Comment by muffinmad** [comment]
> > Or is it has some drawbacks?
> 
> Apart from readability, no. Perhaps a comment would help convey the intention.

@basil-conto Indeed. Added in https://github.com/muffinmad/emacs-ibuffer-project/commit/38d0d528f7ec008d2953fc9c6217b327c50088ec. Thank you!
