### ISSUE TITLE
Extract project root using (car (project-roots (project-current nil dir)))

### ISSUE THREAD

**Issue by YangZhao11** [muffinmad/emacs-ibuffer-project#4]
In the default value of `ibuffer-project-root-functions`, the lambda to extract project root directory assumes a certain format (used by project type vc) for the project. 

Project.el actually allows different data format for different project backends. It also provides a `project-roots` function, which returns a list (but usually should contain only one item). In emacs 28, `project-roots` is deprecated in favor of `project-root`, which returns a single directory.  Until emacs 28 become mainstream, we'll still need to use `project-roots` for the time being.

**Comment by muffinmad** [comment]
Thanks! Must be fixed now.

**Comment by Ergus** [comment]
Hi:

I think it is time to switch this already to `project-root`

 Also `ibuffer-awhen` is obsolete and must use `when-let` instead.
 same for `ibuffer-remove-duplicates` to `seq-uniq`
